
[app]
name          = "gateway"
project       = "nbc-chat"
env           = "prod"
debug         = false
http_code     = "json"
tcp_code      = "protobuf"

[server]
bind_interface = ""

[server.http]
host           = "0.0.0.0"
port           = 10800
gzip           = true
pprof          = true
